language: minimal

notifications:
  email: false

before_script:
- wget 'https://docs.google.com/spreadsheets/d/e/2PACX-1vScL-x9_AoT-nZ8vbQXsnl94p-jbBNWSXqj1UYzP-wGtTJSsvW4hDQhA2xPsGbo6udSt9pP6aiwa5j3/pub?gid=0&single=true&output=csv' -O _data/antidoto.csv
