language: minimal

notifications:
  email: false

before_script:
- wget 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQssPMP5qhidmF0jvycd2IYtm2PP8pPiFjKRcADwdtXUZHEOyNiwy6kDZJ6DOq_gB2qV4ehd3arVgnA/pub?gid=0&single=true&output=csv' -O _data/antidoto.csv

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
